version: 1.0.'{build}'

image:
 - ubuntu1804
 - Visual Studio 2017

configuration: Release

platform: x64

stack: jdk 11

for:
 -
  matrix:
    only:
      - image: ubuntu1804
  environment:    
    VCPKG_ROOT: /usr/local/share/vcpkg
    CC: gcc-8
    CXX: g++-8
 -
  matrix:
    only:
      - image: Visual Studio 2017
  environment:
    VCPKG_ROOT: C:\tools\vcpkg

build_script:
  - sh: |
         mkdir -p /usr/local/share
         cd /usr/local/share
         git clone https://github.com/Microsoft/vcpkg.git
         ./bootstrap-vcpkg.sh
         ./vcpkg integrate install
         cp -f $APPVEYOR_BUILD_FOLDER/vcpkg/libuv/* $VCPKG_ROOT/ports/libuv
         ./vcpkg install libuv:x64-linux
         cd $APPVEYOR_BUILD_FOLDER/src/main
         ./build.sh
         java -version
         cd $APPVEYOR_BUILD_FOLDER
         mvn -DskipTests -q package
  - cmd: copy /Y %APPVEYOR_BUILD_FOLDER%\vcpkg\libuv %VCPKG_ROOT%\ports\libuv
  - cmd: vcpkg.exe install libuv:x64-windows-static
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\src\main && build.bat
  - cmd: java -version
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && mvn -DskipTests -q package

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER% && mvn -q surefire-report:report
  - sh: cd $APPVEYOR_BUILD_FOLDER && mvn -q surefire-report:report

after_test:
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        Get-ChildItem . -Name -Recurse 'TEST-*.xml'  |
        Foreach-Object {
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
        }
artifacts:
  - path: target/libuv-java-1.0.0.jar
    name: libuv-java library