/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oracle_libuv_NativeException */

#ifndef _Included_com_oracle_libuv_NativeException
#define _Included_com_oracle_libuv_NativeException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_oracle_libuv_NativeException_serialVersionUID
#define com_oracle_libuv_NativeException_serialVersionUID -3042686055658047285i64
#undef com_oracle_libuv_NativeException_serialVersionUID
#define com_oracle_libuv_NativeException_serialVersionUID -3387516993124229948i64
#undef com_oracle_libuv_NativeException_serialVersionUID
#define com_oracle_libuv_NativeException_serialVersionUID -7034897190745766939i64
/*
 * Class:     com_oracle_libuv_NativeException
 * Method:    _static_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_oracle_libuv_NativeException__1static_1initialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
