/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oracle_libuv_handles_PrepareHandle */

#ifndef _Included_com_oracle_libuv_handles_PrepareHandle
#define _Included_com_oracle_libuv_handles_PrepareHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oracle_libuv_handles_PrepareHandle
 * Method:    _new
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_oracle_libuv_handles_PrepareHandle__1new
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_oracle_libuv_handles_PrepareHandle
 * Method:    _static_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_oracle_libuv_handles_PrepareHandle__1static_1initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_oracle_libuv_handles_PrepareHandle
 * Method:    _initialize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_oracle_libuv_handles_PrepareHandle__1initialize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_oracle_libuv_handles_PrepareHandle
 * Method:    _start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_oracle_libuv_handles_PrepareHandle__1start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_oracle_libuv_handles_PrepareHandle
 * Method:    _stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_oracle_libuv_handles_PrepareHandle__1stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_oracle_libuv_handles_PrepareHandle
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_oracle_libuv_handles_PrepareHandle__1close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
